global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'eureka'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eureka:8761']

  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway:9000']

  - job_name: 'authentication'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['authentication:8091']

  - job_name: 'produk'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['produk:8081']

  - job_name: 'pelanggan'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['pelanggan:8082']

  - job_name: 'order'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order:8083']

  - job_name: 'produser'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['produser:8080']

  - job_name: 'consumer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['consumer:8084']

  - job_name: 'notification'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification:8080']